version: '3.8'

services:
  # Base de données PostgreSQL
  db:
    image: postgres:15
    container_name: odoo_simple_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password_secure
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

  # Application Odoo (image standard)
  odoo:
    image: odoo:17.0
    container_name: odoo_simple_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_password_secure
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: unless-stopped
    command: odoo

volumes:
  odoo-web-data:
  odoo-db-data: